### ISSUE TITLE
Question about improvement

### ISSUE THREAD

**Issue by Olizja** [enthus1ast/chromeDisableWebrtc#1]
With the extension installed in Google chrome, this item is active - https://browserleaks.com/webrtc
Screenshot - https://imgur.com/fXPqQf3
Does this affect privacy and if so, can you fix it?

Also with this extension, my ip is visible on this site - https://gologin.com/check-browser 
Screenshot - https://imgur.com/z7gpnCi
But if I additionally install another of your " https://github.com/sgreben/web-rtc-disable_non_proxied_udp " extensions, then the ip is hidden.  https://imgur.com/Bkn4zy1
So I use two extensions.

**Comment by enthus1ast** [comment]
i don't know why it showed true on RTCPeerConnection

because this fails (as intended):
```js
localConnection = new RTCPeerConnection();

sendChannel = localConnection.createDataChannel("sendChannel");
sendChannel.onopen = handleSendChannelStatusChange;
sendChannel.onclose = handleSendChannelStatusChange;
```

**Comment by Olizja** [comment]
If this is how it should be, then close the question.

*Additional question. Is it normal to use using two of your extensions?

**Comment by enthus1ast** [comment]
The second one is not mine

**Comment by Olizja** [comment]
Then I don't know what to answer.

**Comment by enthus1ast** [comment]
and it seems that the function override is not working properly any more...
If you like, fix it :) pr's welcome

**Comment by Olizja** [comment]
I would love to, but I don't know how
